// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package g

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                   = new(Query)
	SBookName           *sBookName
	SChinesePicture     *sChinesePicture
	SChinesePictureInfo *sChinesePictureInfo
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	SBookName = &Q.SBookName
	SChinesePicture = &Q.SChinesePicture
	SChinesePictureInfo = &Q.SChinesePictureInfo
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                  db,
		SBookName:           newSBookName(db, opts...),
		SChinesePicture:     newSChinesePicture(db, opts...),
		SChinesePictureInfo: newSChinesePictureInfo(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	SBookName           sBookName
	SChinesePicture     sChinesePicture
	SChinesePictureInfo sChinesePictureInfo
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                  db,
		SBookName:           q.SBookName.clone(db),
		SChinesePicture:     q.SChinesePicture.clone(db),
		SChinesePictureInfo: q.SChinesePictureInfo.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                  db,
		SBookName:           q.SBookName.replaceDB(db),
		SChinesePicture:     q.SChinesePicture.replaceDB(db),
		SChinesePictureInfo: q.SChinesePictureInfo.replaceDB(db),
	}
}

type queryCtx struct {
	SBookName           ISBookNameDo
	SChinesePicture     ISChinesePictureDo
	SChinesePictureInfo ISChinesePictureInfoDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		SBookName:           q.SBookName.WithContext(ctx),
		SChinesePicture:     q.SChinesePicture.WithContext(ctx),
		SChinesePictureInfo: q.SChinesePictureInfo.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
