// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package g

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"crm/internal/model"
)

func newSBookName(db *gorm.DB, opts ...gen.DOOption) sBookName {
	_sBookName := sBookName{}

	_sBookName.sBookNameDo.UseDB(db, opts...)
	_sBookName.sBookNameDo.UseModel(&model.SBookName{})

	tableName := _sBookName.sBookNameDo.TableName()
	_sBookName.ALL = field.NewAsterisk(tableName)
	_sBookName.Id = field.NewInt(tableName, "id")
	_sBookName.CategoryId = field.NewInt(tableName, "category_id")
	_sBookName.Name = field.NewString(tableName, "name")
	_sBookName.SSort = field.NewInt(tableName, "s_sort")
	_sBookName.SType = field.NewInt(tableName, "s_type")
	_sBookName.Status = field.NewInt(tableName, "status")

	_sBookName.fillFieldMap()

	return _sBookName
}

type sBookName struct {
	sBookNameDo

	ALL        field.Asterisk
	Id         field.Int    // 主键
	CategoryId field.Int    // 类型
	Name       field.String // 名称
	SSort      field.Int    // 排序
	SType      field.Int    // 1中文绘本,2英文绘本,3古诗绘本
	Status     field.Int    // 状态

	fieldMap map[string]field.Expr
}

func (s sBookName) Table(newTableName string) *sBookName {
	s.sBookNameDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sBookName) As(alias string) *sBookName {
	s.sBookNameDo.DO = *(s.sBookNameDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sBookName) updateTableName(table string) *sBookName {
	s.ALL = field.NewAsterisk(table)
	s.Id = field.NewInt(table, "id")
	s.CategoryId = field.NewInt(table, "category_id")
	s.Name = field.NewString(table, "name")
	s.SSort = field.NewInt(table, "s_sort")
	s.SType = field.NewInt(table, "s_type")
	s.Status = field.NewInt(table, "status")

	s.fillFieldMap()

	return s
}

func (s *sBookName) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sBookName) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 6)
	s.fieldMap["id"] = s.Id
	s.fieldMap["category_id"] = s.CategoryId
	s.fieldMap["name"] = s.Name
	s.fieldMap["s_sort"] = s.SSort
	s.fieldMap["s_type"] = s.SType
	s.fieldMap["status"] = s.Status
}

func (s sBookName) clone(db *gorm.DB) sBookName {
	s.sBookNameDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sBookName) replaceDB(db *gorm.DB) sBookName {
	s.sBookNameDo.ReplaceDB(db)
	return s
}

type sBookNameDo struct{ gen.DO }

type ISBookNameDo interface {
	gen.SubQuery
	Debug() ISBookNameDo
	WithContext(ctx context.Context) ISBookNameDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISBookNameDo
	WriteDB() ISBookNameDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISBookNameDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISBookNameDo
	Not(conds ...gen.Condition) ISBookNameDo
	Or(conds ...gen.Condition) ISBookNameDo
	Select(conds ...field.Expr) ISBookNameDo
	Where(conds ...gen.Condition) ISBookNameDo
	Order(conds ...field.Expr) ISBookNameDo
	Distinct(cols ...field.Expr) ISBookNameDo
	Omit(cols ...field.Expr) ISBookNameDo
	Join(table schema.Tabler, on ...field.Expr) ISBookNameDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISBookNameDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISBookNameDo
	Group(cols ...field.Expr) ISBookNameDo
	Having(conds ...gen.Condition) ISBookNameDo
	Limit(limit int) ISBookNameDo
	Offset(offset int) ISBookNameDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISBookNameDo
	Unscoped() ISBookNameDo
	Create(values ...*model.SBookName) error
	CreateInBatches(values []*model.SBookName, batchSize int) error
	Save(values ...*model.SBookName) error
	First() (*model.SBookName, error)
	Take() (*model.SBookName, error)
	Last() (*model.SBookName, error)
	Find() ([]*model.SBookName, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SBookName, err error)
	FindInBatches(result *[]*model.SBookName, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SBookName) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISBookNameDo
	Assign(attrs ...field.AssignExpr) ISBookNameDo
	Joins(fields ...field.RelationField) ISBookNameDo
	Preload(fields ...field.RelationField) ISBookNameDo
	FirstOrInit() (*model.SBookName, error)
	FirstOrCreate() (*model.SBookName, error)
	FindByPage(offset int, limit int) (result []*model.SBookName, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISBookNameDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sBookNameDo) Debug() ISBookNameDo {
	return s.withDO(s.DO.Debug())
}

func (s sBookNameDo) WithContext(ctx context.Context) ISBookNameDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sBookNameDo) ReadDB() ISBookNameDo {
	return s.Clauses(dbresolver.Read)
}

func (s sBookNameDo) WriteDB() ISBookNameDo {
	return s.Clauses(dbresolver.Write)
}

func (s sBookNameDo) Session(config *gorm.Session) ISBookNameDo {
	return s.withDO(s.DO.Session(config))
}

func (s sBookNameDo) Clauses(conds ...clause.Expression) ISBookNameDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sBookNameDo) Returning(value interface{}, columns ...string) ISBookNameDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sBookNameDo) Not(conds ...gen.Condition) ISBookNameDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sBookNameDo) Or(conds ...gen.Condition) ISBookNameDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sBookNameDo) Select(conds ...field.Expr) ISBookNameDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sBookNameDo) Where(conds ...gen.Condition) ISBookNameDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sBookNameDo) Order(conds ...field.Expr) ISBookNameDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sBookNameDo) Distinct(cols ...field.Expr) ISBookNameDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sBookNameDo) Omit(cols ...field.Expr) ISBookNameDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sBookNameDo) Join(table schema.Tabler, on ...field.Expr) ISBookNameDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sBookNameDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISBookNameDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sBookNameDo) RightJoin(table schema.Tabler, on ...field.Expr) ISBookNameDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sBookNameDo) Group(cols ...field.Expr) ISBookNameDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sBookNameDo) Having(conds ...gen.Condition) ISBookNameDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sBookNameDo) Limit(limit int) ISBookNameDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sBookNameDo) Offset(offset int) ISBookNameDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sBookNameDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISBookNameDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sBookNameDo) Unscoped() ISBookNameDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sBookNameDo) Create(values ...*model.SBookName) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sBookNameDo) CreateInBatches(values []*model.SBookName, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sBookNameDo) Save(values ...*model.SBookName) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sBookNameDo) First() (*model.SBookName, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SBookName), nil
	}
}

func (s sBookNameDo) Take() (*model.SBookName, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SBookName), nil
	}
}

func (s sBookNameDo) Last() (*model.SBookName, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SBookName), nil
	}
}

func (s sBookNameDo) Find() ([]*model.SBookName, error) {
	result, err := s.DO.Find()
	return result.([]*model.SBookName), err
}

func (s sBookNameDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SBookName, err error) {
	buf := make([]*model.SBookName, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sBookNameDo) FindInBatches(result *[]*model.SBookName, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sBookNameDo) Attrs(attrs ...field.AssignExpr) ISBookNameDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sBookNameDo) Assign(attrs ...field.AssignExpr) ISBookNameDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sBookNameDo) Joins(fields ...field.RelationField) ISBookNameDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sBookNameDo) Preload(fields ...field.RelationField) ISBookNameDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sBookNameDo) FirstOrInit() (*model.SBookName, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SBookName), nil
	}
}

func (s sBookNameDo) FirstOrCreate() (*model.SBookName, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SBookName), nil
	}
}

func (s sBookNameDo) FindByPage(offset int, limit int) (result []*model.SBookName, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sBookNameDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sBookNameDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sBookNameDo) Delete(models ...*model.SBookName) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sBookNameDo) withDO(do gen.Dao) *sBookNameDo {
	s.DO = *do.(*gen.DO)
	return s
}
