// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package g

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"crm/internal/model"
)

func newSChinesePictureInfo(db *gorm.DB, opts ...gen.DOOption) sChinesePictureInfo {
	_sChinesePictureInfo := sChinesePictureInfo{}

	_sChinesePictureInfo.sChinesePictureInfoDo.UseDB(db, opts...)
	_sChinesePictureInfo.sChinesePictureInfoDo.UseModel(&model.SChinesePictureInfo{})

	tableName := _sChinesePictureInfo.sChinesePictureInfoDo.TableName()
	_sChinesePictureInfo.ALL = field.NewAsterisk(tableName)
	_sChinesePictureInfo.Id = field.NewUint(tableName, "id")
	_sChinesePictureInfo.BookId = field.NewString(tableName, "book_id")
	_sChinesePictureInfo.BookIdOld = field.NewUint(tableName, "book_id_old")
	_sChinesePictureInfo.Pic = field.NewString(tableName, "pic")
	_sChinesePictureInfo.Position = field.NewInt(tableName, "position")
	_sChinesePictureInfo.Mp3 = field.NewString(tableName, "mp3")
	_sChinesePictureInfo.Status = field.NewInt(tableName, "status")

	_sChinesePictureInfo.fillFieldMap()

	return _sChinesePictureInfo
}

type sChinesePictureInfo struct {
	sChinesePictureInfoDo

	ALL       field.Asterisk
	Id        field.Uint   // 主键id
	BookId    field.String // 绘本id
	BookIdOld field.Uint   // 绘本id
	Pic       field.String // 详情图
	Position  field.Int    // 排序位置
	Mp3       field.String // Mp3
	Status    field.Int    // 启用状态，1启用,0禁用

	fieldMap map[string]field.Expr
}

func (s sChinesePictureInfo) Table(newTableName string) *sChinesePictureInfo {
	s.sChinesePictureInfoDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sChinesePictureInfo) As(alias string) *sChinesePictureInfo {
	s.sChinesePictureInfoDo.DO = *(s.sChinesePictureInfoDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sChinesePictureInfo) updateTableName(table string) *sChinesePictureInfo {
	s.ALL = field.NewAsterisk(table)
	s.Id = field.NewUint(table, "id")
	s.BookId = field.NewString(table, "book_id")
	s.BookIdOld = field.NewUint(table, "book_id_old")
	s.Pic = field.NewString(table, "pic")
	s.Position = field.NewInt(table, "position")
	s.Mp3 = field.NewString(table, "mp3")
	s.Status = field.NewInt(table, "status")

	s.fillFieldMap()

	return s
}

func (s *sChinesePictureInfo) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sChinesePictureInfo) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 7)
	s.fieldMap["id"] = s.Id
	s.fieldMap["book_id"] = s.BookId
	s.fieldMap["book_id_old"] = s.BookIdOld
	s.fieldMap["pic"] = s.Pic
	s.fieldMap["position"] = s.Position
	s.fieldMap["mp3"] = s.Mp3
	s.fieldMap["status"] = s.Status
}

func (s sChinesePictureInfo) clone(db *gorm.DB) sChinesePictureInfo {
	s.sChinesePictureInfoDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sChinesePictureInfo) replaceDB(db *gorm.DB) sChinesePictureInfo {
	s.sChinesePictureInfoDo.ReplaceDB(db)
	return s
}

type sChinesePictureInfoDo struct{ gen.DO }

type ISChinesePictureInfoDo interface {
	gen.SubQuery
	Debug() ISChinesePictureInfoDo
	WithContext(ctx context.Context) ISChinesePictureInfoDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISChinesePictureInfoDo
	WriteDB() ISChinesePictureInfoDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISChinesePictureInfoDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISChinesePictureInfoDo
	Not(conds ...gen.Condition) ISChinesePictureInfoDo
	Or(conds ...gen.Condition) ISChinesePictureInfoDo
	Select(conds ...field.Expr) ISChinesePictureInfoDo
	Where(conds ...gen.Condition) ISChinesePictureInfoDo
	Order(conds ...field.Expr) ISChinesePictureInfoDo
	Distinct(cols ...field.Expr) ISChinesePictureInfoDo
	Omit(cols ...field.Expr) ISChinesePictureInfoDo
	Join(table schema.Tabler, on ...field.Expr) ISChinesePictureInfoDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISChinesePictureInfoDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISChinesePictureInfoDo
	Group(cols ...field.Expr) ISChinesePictureInfoDo
	Having(conds ...gen.Condition) ISChinesePictureInfoDo
	Limit(limit int) ISChinesePictureInfoDo
	Offset(offset int) ISChinesePictureInfoDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISChinesePictureInfoDo
	Unscoped() ISChinesePictureInfoDo
	Create(values ...*model.SChinesePictureInfo) error
	CreateInBatches(values []*model.SChinesePictureInfo, batchSize int) error
	Save(values ...*model.SChinesePictureInfo) error
	First() (*model.SChinesePictureInfo, error)
	Take() (*model.SChinesePictureInfo, error)
	Last() (*model.SChinesePictureInfo, error)
	Find() ([]*model.SChinesePictureInfo, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SChinesePictureInfo, err error)
	FindInBatches(result *[]*model.SChinesePictureInfo, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SChinesePictureInfo) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISChinesePictureInfoDo
	Assign(attrs ...field.AssignExpr) ISChinesePictureInfoDo
	Joins(fields ...field.RelationField) ISChinesePictureInfoDo
	Preload(fields ...field.RelationField) ISChinesePictureInfoDo
	FirstOrInit() (*model.SChinesePictureInfo, error)
	FirstOrCreate() (*model.SChinesePictureInfo, error)
	FindByPage(offset int, limit int) (result []*model.SChinesePictureInfo, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISChinesePictureInfoDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sChinesePictureInfoDo) Debug() ISChinesePictureInfoDo {
	return s.withDO(s.DO.Debug())
}

func (s sChinesePictureInfoDo) WithContext(ctx context.Context) ISChinesePictureInfoDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sChinesePictureInfoDo) ReadDB() ISChinesePictureInfoDo {
	return s.Clauses(dbresolver.Read)
}

func (s sChinesePictureInfoDo) WriteDB() ISChinesePictureInfoDo {
	return s.Clauses(dbresolver.Write)
}

func (s sChinesePictureInfoDo) Session(config *gorm.Session) ISChinesePictureInfoDo {
	return s.withDO(s.DO.Session(config))
}

func (s sChinesePictureInfoDo) Clauses(conds ...clause.Expression) ISChinesePictureInfoDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sChinesePictureInfoDo) Returning(value interface{}, columns ...string) ISChinesePictureInfoDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sChinesePictureInfoDo) Not(conds ...gen.Condition) ISChinesePictureInfoDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sChinesePictureInfoDo) Or(conds ...gen.Condition) ISChinesePictureInfoDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sChinesePictureInfoDo) Select(conds ...field.Expr) ISChinesePictureInfoDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sChinesePictureInfoDo) Where(conds ...gen.Condition) ISChinesePictureInfoDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sChinesePictureInfoDo) Order(conds ...field.Expr) ISChinesePictureInfoDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sChinesePictureInfoDo) Distinct(cols ...field.Expr) ISChinesePictureInfoDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sChinesePictureInfoDo) Omit(cols ...field.Expr) ISChinesePictureInfoDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sChinesePictureInfoDo) Join(table schema.Tabler, on ...field.Expr) ISChinesePictureInfoDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sChinesePictureInfoDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISChinesePictureInfoDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sChinesePictureInfoDo) RightJoin(table schema.Tabler, on ...field.Expr) ISChinesePictureInfoDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sChinesePictureInfoDo) Group(cols ...field.Expr) ISChinesePictureInfoDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sChinesePictureInfoDo) Having(conds ...gen.Condition) ISChinesePictureInfoDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sChinesePictureInfoDo) Limit(limit int) ISChinesePictureInfoDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sChinesePictureInfoDo) Offset(offset int) ISChinesePictureInfoDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sChinesePictureInfoDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISChinesePictureInfoDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sChinesePictureInfoDo) Unscoped() ISChinesePictureInfoDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sChinesePictureInfoDo) Create(values ...*model.SChinesePictureInfo) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sChinesePictureInfoDo) CreateInBatches(values []*model.SChinesePictureInfo, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sChinesePictureInfoDo) Save(values ...*model.SChinesePictureInfo) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sChinesePictureInfoDo) First() (*model.SChinesePictureInfo, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SChinesePictureInfo), nil
	}
}

func (s sChinesePictureInfoDo) Take() (*model.SChinesePictureInfo, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SChinesePictureInfo), nil
	}
}

func (s sChinesePictureInfoDo) Last() (*model.SChinesePictureInfo, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SChinesePictureInfo), nil
	}
}

func (s sChinesePictureInfoDo) Find() ([]*model.SChinesePictureInfo, error) {
	result, err := s.DO.Find()
	return result.([]*model.SChinesePictureInfo), err
}

func (s sChinesePictureInfoDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SChinesePictureInfo, err error) {
	buf := make([]*model.SChinesePictureInfo, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sChinesePictureInfoDo) FindInBatches(result *[]*model.SChinesePictureInfo, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sChinesePictureInfoDo) Attrs(attrs ...field.AssignExpr) ISChinesePictureInfoDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sChinesePictureInfoDo) Assign(attrs ...field.AssignExpr) ISChinesePictureInfoDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sChinesePictureInfoDo) Joins(fields ...field.RelationField) ISChinesePictureInfoDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sChinesePictureInfoDo) Preload(fields ...field.RelationField) ISChinesePictureInfoDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sChinesePictureInfoDo) FirstOrInit() (*model.SChinesePictureInfo, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SChinesePictureInfo), nil
	}
}

func (s sChinesePictureInfoDo) FirstOrCreate() (*model.SChinesePictureInfo, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SChinesePictureInfo), nil
	}
}

func (s sChinesePictureInfoDo) FindByPage(offset int, limit int) (result []*model.SChinesePictureInfo, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sChinesePictureInfoDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sChinesePictureInfoDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sChinesePictureInfoDo) Delete(models ...*model.SChinesePictureInfo) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sChinesePictureInfoDo) withDO(do gen.Dao) *sChinesePictureInfoDo {
	s.DO = *do.(*gen.DO)
	return s
}
