// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package g

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"crm/internal/model"
)

func newSChinesePicture(db *gorm.DB, opts ...gen.DOOption) sChinesePicture {
	_sChinesePicture := sChinesePicture{}

	_sChinesePicture.sChinesePictureDo.UseDB(db, opts...)
	_sChinesePicture.sChinesePictureDo.UseModel(&model.SChinesePicture{})

	tableName := _sChinesePicture.sChinesePictureDo.TableName()
	_sChinesePicture.ALL = field.NewAsterisk(tableName)
	_sChinesePicture.Id = field.NewInt(tableName, "id")
	_sChinesePicture.BookId = field.NewString(tableName, "book_id")
	_sChinesePicture.BookIdOld = field.NewUint(tableName, "book_id_old")
	_sChinesePicture.Title = field.NewString(tableName, "title")
	_sChinesePicture.Icon1 = field.NewString(tableName, "icon_1")
	_sChinesePicture.Icon = field.NewString(tableName, "icon")
	_sChinesePicture.Type = field.NewInt(tableName, "type")
	_sChinesePicture.Position = field.NewInt(tableName, "position")
	_sChinesePicture.Status = field.NewInt(tableName, "status")

	_sChinesePicture.fillFieldMap()

	return _sChinesePicture
}

type sChinesePicture struct {
	sChinesePictureDo

	ALL       field.Asterisk
	Id        field.Int    // 主键
	BookId    field.String // 绘本id
	BookIdOld field.Uint   // 绘本id
	Title     field.String // 标题
	Icon1     field.String // 封面图
	Icon      field.String // 封面图
	Type      field.Int    // 类型
	Position  field.Int    // 排序位置
	Status    field.Int    // 启用状态，1启用,0禁用

	fieldMap map[string]field.Expr
}

func (s sChinesePicture) Table(newTableName string) *sChinesePicture {
	s.sChinesePictureDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sChinesePicture) As(alias string) *sChinesePicture {
	s.sChinesePictureDo.DO = *(s.sChinesePictureDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sChinesePicture) updateTableName(table string) *sChinesePicture {
	s.ALL = field.NewAsterisk(table)
	s.Id = field.NewInt(table, "id")
	s.BookId = field.NewString(table, "book_id")
	s.BookIdOld = field.NewUint(table, "book_id_old")
	s.Title = field.NewString(table, "title")
	s.Icon1 = field.NewString(table, "icon_1")
	s.Icon = field.NewString(table, "icon")
	s.Type = field.NewInt(table, "type")
	s.Position = field.NewInt(table, "position")
	s.Status = field.NewInt(table, "status")

	s.fillFieldMap()

	return s
}

func (s *sChinesePicture) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sChinesePicture) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 9)
	s.fieldMap["id"] = s.Id
	s.fieldMap["book_id"] = s.BookId
	s.fieldMap["book_id_old"] = s.BookIdOld
	s.fieldMap["title"] = s.Title
	s.fieldMap["icon_1"] = s.Icon1
	s.fieldMap["icon"] = s.Icon
	s.fieldMap["type"] = s.Type
	s.fieldMap["position"] = s.Position
	s.fieldMap["status"] = s.Status
}

func (s sChinesePicture) clone(db *gorm.DB) sChinesePicture {
	s.sChinesePictureDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sChinesePicture) replaceDB(db *gorm.DB) sChinesePicture {
	s.sChinesePictureDo.ReplaceDB(db)
	return s
}

type sChinesePictureDo struct{ gen.DO }

type ISChinesePictureDo interface {
	gen.SubQuery
	Debug() ISChinesePictureDo
	WithContext(ctx context.Context) ISChinesePictureDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISChinesePictureDo
	WriteDB() ISChinesePictureDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISChinesePictureDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISChinesePictureDo
	Not(conds ...gen.Condition) ISChinesePictureDo
	Or(conds ...gen.Condition) ISChinesePictureDo
	Select(conds ...field.Expr) ISChinesePictureDo
	Where(conds ...gen.Condition) ISChinesePictureDo
	Order(conds ...field.Expr) ISChinesePictureDo
	Distinct(cols ...field.Expr) ISChinesePictureDo
	Omit(cols ...field.Expr) ISChinesePictureDo
	Join(table schema.Tabler, on ...field.Expr) ISChinesePictureDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISChinesePictureDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISChinesePictureDo
	Group(cols ...field.Expr) ISChinesePictureDo
	Having(conds ...gen.Condition) ISChinesePictureDo
	Limit(limit int) ISChinesePictureDo
	Offset(offset int) ISChinesePictureDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISChinesePictureDo
	Unscoped() ISChinesePictureDo
	Create(values ...*model.SChinesePicture) error
	CreateInBatches(values []*model.SChinesePicture, batchSize int) error
	Save(values ...*model.SChinesePicture) error
	First() (*model.SChinesePicture, error)
	Take() (*model.SChinesePicture, error)
	Last() (*model.SChinesePicture, error)
	Find() ([]*model.SChinesePicture, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SChinesePicture, err error)
	FindInBatches(result *[]*model.SChinesePicture, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SChinesePicture) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISChinesePictureDo
	Assign(attrs ...field.AssignExpr) ISChinesePictureDo
	Joins(fields ...field.RelationField) ISChinesePictureDo
	Preload(fields ...field.RelationField) ISChinesePictureDo
	FirstOrInit() (*model.SChinesePicture, error)
	FirstOrCreate() (*model.SChinesePicture, error)
	FindByPage(offset int, limit int) (result []*model.SChinesePicture, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISChinesePictureDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sChinesePictureDo) Debug() ISChinesePictureDo {
	return s.withDO(s.DO.Debug())
}

func (s sChinesePictureDo) WithContext(ctx context.Context) ISChinesePictureDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sChinesePictureDo) ReadDB() ISChinesePictureDo {
	return s.Clauses(dbresolver.Read)
}

func (s sChinesePictureDo) WriteDB() ISChinesePictureDo {
	return s.Clauses(dbresolver.Write)
}

func (s sChinesePictureDo) Session(config *gorm.Session) ISChinesePictureDo {
	return s.withDO(s.DO.Session(config))
}

func (s sChinesePictureDo) Clauses(conds ...clause.Expression) ISChinesePictureDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sChinesePictureDo) Returning(value interface{}, columns ...string) ISChinesePictureDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sChinesePictureDo) Not(conds ...gen.Condition) ISChinesePictureDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sChinesePictureDo) Or(conds ...gen.Condition) ISChinesePictureDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sChinesePictureDo) Select(conds ...field.Expr) ISChinesePictureDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sChinesePictureDo) Where(conds ...gen.Condition) ISChinesePictureDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sChinesePictureDo) Order(conds ...field.Expr) ISChinesePictureDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sChinesePictureDo) Distinct(cols ...field.Expr) ISChinesePictureDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sChinesePictureDo) Omit(cols ...field.Expr) ISChinesePictureDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sChinesePictureDo) Join(table schema.Tabler, on ...field.Expr) ISChinesePictureDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sChinesePictureDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISChinesePictureDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sChinesePictureDo) RightJoin(table schema.Tabler, on ...field.Expr) ISChinesePictureDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sChinesePictureDo) Group(cols ...field.Expr) ISChinesePictureDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sChinesePictureDo) Having(conds ...gen.Condition) ISChinesePictureDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sChinesePictureDo) Limit(limit int) ISChinesePictureDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sChinesePictureDo) Offset(offset int) ISChinesePictureDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sChinesePictureDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISChinesePictureDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sChinesePictureDo) Unscoped() ISChinesePictureDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sChinesePictureDo) Create(values ...*model.SChinesePicture) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sChinesePictureDo) CreateInBatches(values []*model.SChinesePicture, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sChinesePictureDo) Save(values ...*model.SChinesePicture) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sChinesePictureDo) First() (*model.SChinesePicture, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SChinesePicture), nil
	}
}

func (s sChinesePictureDo) Take() (*model.SChinesePicture, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SChinesePicture), nil
	}
}

func (s sChinesePictureDo) Last() (*model.SChinesePicture, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SChinesePicture), nil
	}
}

func (s sChinesePictureDo) Find() ([]*model.SChinesePicture, error) {
	result, err := s.DO.Find()
	return result.([]*model.SChinesePicture), err
}

func (s sChinesePictureDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SChinesePicture, err error) {
	buf := make([]*model.SChinesePicture, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sChinesePictureDo) FindInBatches(result *[]*model.SChinesePicture, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sChinesePictureDo) Attrs(attrs ...field.AssignExpr) ISChinesePictureDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sChinesePictureDo) Assign(attrs ...field.AssignExpr) ISChinesePictureDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sChinesePictureDo) Joins(fields ...field.RelationField) ISChinesePictureDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sChinesePictureDo) Preload(fields ...field.RelationField) ISChinesePictureDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sChinesePictureDo) FirstOrInit() (*model.SChinesePicture, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SChinesePicture), nil
	}
}

func (s sChinesePictureDo) FirstOrCreate() (*model.SChinesePicture, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SChinesePicture), nil
	}
}

func (s sChinesePictureDo) FindByPage(offset int, limit int) (result []*model.SChinesePicture, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sChinesePictureDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sChinesePictureDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sChinesePictureDo) Delete(models ...*model.SChinesePicture) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sChinesePictureDo) withDO(do gen.Dao) *sChinesePictureDo {
	s.DO = *do.(*gen.DO)
	return s
}
