// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package g

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"crm/internal/model"
)

func newSPictureCategory(db *gorm.DB, opts ...gen.DOOption) sPictureCategory {
	_sPictureCategory := sPictureCategory{}

	_sPictureCategory.sPictureCategoryDo.UseDB(db, opts...)
	_sPictureCategory.sPictureCategoryDo.UseModel(&model.SPictureCategory{})

	tableName := _sPictureCategory.sPictureCategoryDo.TableName()
	_sPictureCategory.ALL = field.NewAsterisk(tableName)
	_sPictureCategory.Id = field.NewUint64(tableName, "id")
	_sPictureCategory.CategoryId = field.NewString(tableName, "category_id")
	_sPictureCategory.CategoryIdOld = field.NewInt(tableName, "category_id_old")
	_sPictureCategory.CategoryName = field.NewString(tableName, "category_name")
	_sPictureCategory.Position = field.NewInt(tableName, "position")
	_sPictureCategory.Type = field.NewString(tableName, "type")
	_sPictureCategory.Status = field.NewString(tableName, "status")
	_sPictureCategory.CreatedAt = field.NewTime(tableName, "created_at")
	_sPictureCategory.UpdatedAt = field.NewTime(tableName, "updated_at")

	_sPictureCategory.fillFieldMap()

	return _sPictureCategory
}

type sPictureCategory struct {
	sPictureCategoryDo

	ALL           field.Asterisk
	Id            field.Uint64 // 主键id
	CategoryId    field.String // 栏目ID
	CategoryIdOld field.Int    // 类型
	CategoryName  field.String // 栏目名称
	Position      field.Int    // 排序,倒序
	Type          field.String // 类型,chinese中文绘本,english英文绘本,poem古诗,word词汇
	Status        field.String // 状态,on启用,off禁用
	CreatedAt     field.Time   // 添加时间
	UpdatedAt     field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (s sPictureCategory) Table(newTableName string) *sPictureCategory {
	s.sPictureCategoryDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sPictureCategory) As(alias string) *sPictureCategory {
	s.sPictureCategoryDo.DO = *(s.sPictureCategoryDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sPictureCategory) updateTableName(table string) *sPictureCategory {
	s.ALL = field.NewAsterisk(table)
	s.Id = field.NewUint64(table, "id")
	s.CategoryId = field.NewString(table, "category_id")
	s.CategoryIdOld = field.NewInt(table, "category_id_old")
	s.CategoryName = field.NewString(table, "category_name")
	s.Position = field.NewInt(table, "position")
	s.Type = field.NewString(table, "type")
	s.Status = field.NewString(table, "status")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")

	s.fillFieldMap()

	return s
}

func (s *sPictureCategory) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sPictureCategory) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 9)
	s.fieldMap["id"] = s.Id
	s.fieldMap["category_id"] = s.CategoryId
	s.fieldMap["category_id_old"] = s.CategoryIdOld
	s.fieldMap["category_name"] = s.CategoryName
	s.fieldMap["position"] = s.Position
	s.fieldMap["type"] = s.Type
	s.fieldMap["status"] = s.Status
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
}

func (s sPictureCategory) clone(db *gorm.DB) sPictureCategory {
	s.sPictureCategoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sPictureCategory) replaceDB(db *gorm.DB) sPictureCategory {
	s.sPictureCategoryDo.ReplaceDB(db)
	return s
}

type sPictureCategoryDo struct{ gen.DO }

type ISPictureCategoryDo interface {
	gen.SubQuery
	Debug() ISPictureCategoryDo
	WithContext(ctx context.Context) ISPictureCategoryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISPictureCategoryDo
	WriteDB() ISPictureCategoryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISPictureCategoryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISPictureCategoryDo
	Not(conds ...gen.Condition) ISPictureCategoryDo
	Or(conds ...gen.Condition) ISPictureCategoryDo
	Select(conds ...field.Expr) ISPictureCategoryDo
	Where(conds ...gen.Condition) ISPictureCategoryDo
	Order(conds ...field.Expr) ISPictureCategoryDo
	Distinct(cols ...field.Expr) ISPictureCategoryDo
	Omit(cols ...field.Expr) ISPictureCategoryDo
	Join(table schema.Tabler, on ...field.Expr) ISPictureCategoryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISPictureCategoryDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISPictureCategoryDo
	Group(cols ...field.Expr) ISPictureCategoryDo
	Having(conds ...gen.Condition) ISPictureCategoryDo
	Limit(limit int) ISPictureCategoryDo
	Offset(offset int) ISPictureCategoryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISPictureCategoryDo
	Unscoped() ISPictureCategoryDo
	Create(values ...*model.SPictureCategory) error
	CreateInBatches(values []*model.SPictureCategory, batchSize int) error
	Save(values ...*model.SPictureCategory) error
	First() (*model.SPictureCategory, error)
	Take() (*model.SPictureCategory, error)
	Last() (*model.SPictureCategory, error)
	Find() ([]*model.SPictureCategory, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SPictureCategory, err error)
	FindInBatches(result *[]*model.SPictureCategory, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SPictureCategory) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISPictureCategoryDo
	Assign(attrs ...field.AssignExpr) ISPictureCategoryDo
	Joins(fields ...field.RelationField) ISPictureCategoryDo
	Preload(fields ...field.RelationField) ISPictureCategoryDo
	FirstOrInit() (*model.SPictureCategory, error)
	FirstOrCreate() (*model.SPictureCategory, error)
	FindByPage(offset int, limit int) (result []*model.SPictureCategory, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISPictureCategoryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sPictureCategoryDo) Debug() ISPictureCategoryDo {
	return s.withDO(s.DO.Debug())
}

func (s sPictureCategoryDo) WithContext(ctx context.Context) ISPictureCategoryDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sPictureCategoryDo) ReadDB() ISPictureCategoryDo {
	return s.Clauses(dbresolver.Read)
}

func (s sPictureCategoryDo) WriteDB() ISPictureCategoryDo {
	return s.Clauses(dbresolver.Write)
}

func (s sPictureCategoryDo) Session(config *gorm.Session) ISPictureCategoryDo {
	return s.withDO(s.DO.Session(config))
}

func (s sPictureCategoryDo) Clauses(conds ...clause.Expression) ISPictureCategoryDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sPictureCategoryDo) Returning(value interface{}, columns ...string) ISPictureCategoryDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sPictureCategoryDo) Not(conds ...gen.Condition) ISPictureCategoryDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sPictureCategoryDo) Or(conds ...gen.Condition) ISPictureCategoryDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sPictureCategoryDo) Select(conds ...field.Expr) ISPictureCategoryDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sPictureCategoryDo) Where(conds ...gen.Condition) ISPictureCategoryDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sPictureCategoryDo) Order(conds ...field.Expr) ISPictureCategoryDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sPictureCategoryDo) Distinct(cols ...field.Expr) ISPictureCategoryDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sPictureCategoryDo) Omit(cols ...field.Expr) ISPictureCategoryDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sPictureCategoryDo) Join(table schema.Tabler, on ...field.Expr) ISPictureCategoryDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sPictureCategoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISPictureCategoryDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sPictureCategoryDo) RightJoin(table schema.Tabler, on ...field.Expr) ISPictureCategoryDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sPictureCategoryDo) Group(cols ...field.Expr) ISPictureCategoryDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sPictureCategoryDo) Having(conds ...gen.Condition) ISPictureCategoryDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sPictureCategoryDo) Limit(limit int) ISPictureCategoryDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sPictureCategoryDo) Offset(offset int) ISPictureCategoryDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sPictureCategoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISPictureCategoryDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sPictureCategoryDo) Unscoped() ISPictureCategoryDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sPictureCategoryDo) Create(values ...*model.SPictureCategory) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sPictureCategoryDo) CreateInBatches(values []*model.SPictureCategory, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sPictureCategoryDo) Save(values ...*model.SPictureCategory) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sPictureCategoryDo) First() (*model.SPictureCategory, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SPictureCategory), nil
	}
}

func (s sPictureCategoryDo) Take() (*model.SPictureCategory, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SPictureCategory), nil
	}
}

func (s sPictureCategoryDo) Last() (*model.SPictureCategory, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SPictureCategory), nil
	}
}

func (s sPictureCategoryDo) Find() ([]*model.SPictureCategory, error) {
	result, err := s.DO.Find()
	return result.([]*model.SPictureCategory), err
}

func (s sPictureCategoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SPictureCategory, err error) {
	buf := make([]*model.SPictureCategory, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sPictureCategoryDo) FindInBatches(result *[]*model.SPictureCategory, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sPictureCategoryDo) Attrs(attrs ...field.AssignExpr) ISPictureCategoryDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sPictureCategoryDo) Assign(attrs ...field.AssignExpr) ISPictureCategoryDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sPictureCategoryDo) Joins(fields ...field.RelationField) ISPictureCategoryDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sPictureCategoryDo) Preload(fields ...field.RelationField) ISPictureCategoryDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sPictureCategoryDo) FirstOrInit() (*model.SPictureCategory, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SPictureCategory), nil
	}
}

func (s sPictureCategoryDo) FirstOrCreate() (*model.SPictureCategory, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SPictureCategory), nil
	}
}

func (s sPictureCategoryDo) FindByPage(offset int, limit int) (result []*model.SPictureCategory, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sPictureCategoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sPictureCategoryDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sPictureCategoryDo) Delete(models ...*model.SPictureCategory) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sPictureCategoryDo) withDO(do gen.Dao) *sPictureCategoryDo {
	s.DO = *do.(*gen.DO)
	return s
}
